# docker nexus
#  - when using nexus for docker images on KMS, go direct not via proxy
#    which requires used non-secure repositories
---
- name: copy repo definition
  become: true
  copy: src="../files/{{ item }}"  dest="/etc/docker"  mode="0600"
  with_items:
    - daemon.json
