# install python - needed to ansible to work
---
- name: Check for Python
  raw: test -e /usr/bin/python
  changed_when: false
  failed_when: false
  register: check_python

- name: Install Python
  raw: dnf -y install python
  when: check_python.rc != 0

  