# k8s-master host
---
- hosts: all
  vars_files:
    - ../../../../common/ansible/vars/centosVars.yml
    - ../../vars.yml

  vars:
    DISABLE_HOST_FIREWALL: true       # this is because firewall interfers with docker

  pre_tasks:
    - import_tasks: tasks/network.yml
      vars:
        host_ip: "{{ k8smaster_ip }}"
        host_fqdn: "{{ k8smaster_fqdn}}"
    - import_tasks: ../../../../common/ansible/tasks/centosTasks.yml
    - import_tasks: ../../../../common/ansible/tasks/docker_prep.yml

  roles:
  tasks:
    #- import_tasks: tasks/k8s-common.yml
    #  vars:
    #    k8s_hosts:
    #      - { name: "{{ k8smaster_hostname }}", ip: "{{ k8smaster_ip }}", domain: "dev.{{ root_domain}}" }
    #      - { name: "{{ k8sworker1_hostname }}", ip: "{{ k8sworker1_ip }}", domain: "dev.{{ root_domain}}" }
    #      - { name: "{{ k8sworker2_hostname }}", ip: "{{ k8sworker2_ip }}", domain: "dev.{{ root_domain}}" }
    #    this_host_ip: "{{ k8smaster_ip }}"
    #- import_tasks: tasks/k8s-master.yml
    # - name: Setup local network (eth2) - for binding the kubernetes dashboard admin UI
    #   become: true
    #   template: src=../../../../common/ansible/templates/ifcfg.j2 dest=/etc/sysconfig/network-scripts/ifcfg-eth2
    #   vars:
    #     ipinterface:
    #       ifname: eth2
    #       ip: "{{ k8s_cockpit_ip }}"
    #       gateway: "{{ network_gw }}"
    #       dns: "{{ local_dns }}"
    #       netmask: "{{ netmask }}"
    - name: Setup local network (eth3) - for binding the Kong Ingress Controller
      become: true
      template: src=../../../../common/ansible/templates/ifcfg.j2 dest=/etc/sysconfig/network-scripts/ifcfg-eth3
      vars:
        ipinterface:
          ifname: eth3
          ip: "{{ k8s_ingress_ip }}"
          gateway: "{{ network_gw }}"
          dns: "{{ local_dns }}"
          netmask: "{{ netmask }}"
    - import_tasks: tasks/k8s-master-tools.yaml