# kubernetes cluster (k8s) - master tools - e.g. helm and kustomize
---
- name: Install kustomize
  become: true
  shell: cd /usr/local/bin && curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash > /usr/local/bin/kustomize_install.log
  args:
    executable: /bin/bash
    creates: /usr/local/bin/kustomize_install.log
  changed_when: false
