# kubernetes cluster (k8s) - master tools - e.g. helm and kustomize
---
- name: Download kustomize
  become: true
  get_url:
    url: https://api.github.com/repos/kubernetes-sigs/kustomize/tarball/kustomize/v3.5.4
    dest: /usr/local/bin
    mode: '0755'