default_os_packages:
  - { name: epel-release, state: present }
  - { name: net-tools, state: present }
  - { name: bind-utils, state: present }
  - { name: dos2unix, state: present }
  - { name: NetworkManager-glib, state: present }
  - { name: libnm-gtk-devel.x86_64, state: present }
  - { name: nm-connection-editor.x86_64, state: present }
  - { name: libsemanage-python, state: present }
  - { name: policycoreutils-python, state: present }
  - { name: openssl-devel, state: present }
  - { name: libselinux-python, state: present }
  - { name: traceroute, state: present }
  - { name: tcpdump, state: absent }
  - { name: telnet, state: absent }

default_groups:
  - { groupname: wit-admin, gid: 2000 }

default_users:
  - { username: aylingw, uid: 2001, default_group: wit-admin, groups: 'wit-admin' }
