# wikiks
#
# Host dependencies for wiki.js V2 container - e.g. docker volumes, host presented config files et al.
---
- name: Enable wiki inbound on public zone
  become: true
  firewalld:
    state: enabled
    zone: public
    port: "{{ WIKI_PORT }}/tcp"
    permanent: yes
  register: wiki_port_firewalld

- name: Restart firewall for changes to take effect
  become: true
  systemd:
    name: firewalld
    state: restarted
  when: wiki_port_firewalld.changed

# https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux_atomic_host/7/html/managing_containers/using_systemd_with_containers
- name: Install wikijs service
  become: true
  template:
      src: ../templates/wiki-cms.docker.service.j2
      dest: /usr/lib/systemd/system/wozitech-cms.service
      owner: root
      group: root
      mode: 0644
  vars:
    wiki_srv:
      name: "{{  WIKI_CONTAINER_NAME }}"
  register: wiki_service_install

- name: Enable and start wikijs docker service
  become: true
  systemd:
    name: "{{ WIKI_CONTAINER_NAME }}"
    state: started
    enabled: true
    daemon_reload: yes
  when: wiki_service_install.changed
  