# container services
---
- name: Enable CMS inbound on public zone
  become: true
  firewalld:
    state: enabled
    zone: public
    port: "{{ CMS_PORT }}/tcp"
    permanent: yes
  register: cms_port_firewalld

- name: Restart firewall for changes to take effect
  become: true
  systemd:
    name: firewalld
    state: restarted
  when: cms_port_firewalld.changed

# https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux_atomic_host/7/html/managing_containers/using_systemd_with_containers
- name: Install CMS service
  become: true
  template:
      src: ../templates/wozitech-cms.docker.service.j2
      dest: /usr/lib/systemd/system/wozitech-cms.service
      owner: root
      group: root
      mode: 0644
  vars:
    cms_srv:
      name: "{{  CMS_CONTAINER_NAME }}"
  register: cms_service_install

- name: Enable and start CMS docker service
  become: true
  systemd:
    name: "{{ CMS_CONTAINER_NAME }}"
    state: started
    enabled: true
    daemon_reload: yes
  when: cms_service_install.changed
