# proxy host
# https://github.com/diafygi/acme-tiny - Lets Encrypt helper
# https://github.com/jwilder/nginx-proxy - nginx with LetS Encyrpt as a docker image
---
- hosts: all
  vars_files:
    - ../../../../common/ansible/vars/centosVars.yml
    - ../../vars.yml

  vars:
    DISABLE_HOST_FIREWALL: true
    NON_SSL_PORT: 80
    SSL_PORT: 443
    SSL_CERTS_DIR: /etc/nginx/certs
    HTML_DIR: /var/www/html
    VHOSTS_DIR: /etc/nginx/vhost.d
    DEFAULT_DOMAIN_NAME: "{{ proxy_fqdn }}"
    NGINX_CONTAINER_NAME: nginx
    VIRTUAL_HOST_WIKI: wozitech.asuscomm.com
    NGINX_PROXY_DEFAULTS_CONF_FILE: /etc/nginx/default_proxy.conf
    NGINX_PROXY_WIKI_CONF_FILE: "{{ VHOSTS_DIR }}/{{ VIRTUAL_HOST_WIKI }}.conf"

  tasks:
    # - import_tasks: tasks/network.yml
    # - import_tasks: ../../../../common/ansible/tasks/centosTasks.yml
    # - import_tasks: ../../../../common/ansible/tasks/docker_prep.yml
    - import_tasks: tasks/nginx.yml
    #- import_tasks: tasks/letsencrypt.yml

