# proxy host
# https://github.com/diafygi/acme-tiny - Lets Encrypt helper
# https://github.com/jwilder/nginx-proxy - nginx with LetS Encyrpt as a docker image
---
- hosts: all
  vars_files:
    - ../../../../common/ansible/vars/centosVars.yml
    - ../../vars.yml

  vars:
    DISABLE_HOST_FIREWALL: true
    NON_SSL_PORT: 80
    SSL_PORT: 443
    NGINX_BASE_DIR: /etc/nginx
    SSL_CERTS_DIR: "{{ NGINX_BASE_DIR }}/certs"
    CONF_CERTS_DIR: "{{ NGINX_BASE_DIR }}/conf"
    HTML_DIR: /var/www/html
    ACME_CHALLENGE_DIR: /var/www/acme
    VHOSTS_CONF_DIR: "{{ NGINX_BASE_DIR }}/conf.d"
    DEFAULT_DOMAIN_NAME: "{{ proxy_fqdn }}"
    NGINX_CONTAINER_NAME: nginx
    LETSENCRYPT_CONTAINER_NAME: letsencrypt
    VIRTUAL_HOST_WIKI: "{{ wiki_external_domain }}"
    NGINX_PROXY_WIKI_CONF_FILE: "{{ VHOSTS_CONF_DIR }}/{{ VIRTUAL_HOST_WIKI }}.conf"
    DHPARAM_FILE: "{{ SSL_CERTS_DIR }}/dhparam.pem"
    REMOTE_WIKI_URI: "http://{{ webserver_ip }}:3000"
    LETENCYRPT_ADMIN_EMAIL: admin@wozitech-ltd.co.uk
    dnsmasq_domain: "{{ root_domain }}"
    dnsmasq_listen_address: "{{ forward_proxy_ip }}"
    dnsmasq_upstream_servers:
      - "{{ root_dns }}"
    dnsmasq_authoritative: true
    dnsmasq_bogus_priv: false      # allows (false) reverse lookups on external IPs
    dnsmasq_srv_hosts:
      - name: _ldap._tcp.example.com
        target: "ldap.{{ root_domain }}"
        port: 389


  pre_tasks:
    # - import_tasks: tasks/network.yml
    - import_tasks: tasks/dns.yml
    # - import_tasks: ../../../../common/ansible/tasks/centosTasks.yml
    # - import_tasks: ../../../../common/ansible/tasks/docker_prep.yml

  roles:
  #  - { role: bertvv.dnsmasq, become: yes }

  tasks:
    # - import_tasks: tasks/nginx.yml
    # - import_tasks: tasks/letsencrypt.yml

