# proxy Let's Encrypt tasks
---

- name: Ensure directory for SSL certs exists
  become: true
  file:
    path: "{{ SSL_CERTS_DIR }}"
    state: directory
    mode: 0750
    owner: root
    group: root

- name: create the LetsEncrypt container
  become: true
  docker_container:
    name: "{{ NGINX_CONTAINER_NAME }}"
    image: jwilder/nginx-proxy:latest
    state: started
    detach: yes
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "{{ SSL_CERTS_DIR }}:/etc/nginx/certs"
    ports:
      - "{{ forward_proxy_ip }}:{{ NON_SSL_PORT }}:{{ NON_SSL_PORT }}/tcp"
      - "{{ forward_proxy_ip }}:{{ SSL_PORT }}:{{ SSL_PORT }}/tcp"
