# proxy Let's Encrypt tasks
---

- name: Ensure directory for target SSL certs exists for the target domain
  become: true
  file:
    path: "{{ SSL_CERTS_DIR }}/{{ wiki_external_domain }}"
    state: directory
    mode: 0750
    owner: root
    group: root

- name: Create directory for local Let's Encrypt config and working data
  become: true
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    owner: root
    group: root
  with_items:
    - /etc/letsencrypt
    - /var/lib/letsencrypt

- name: Create directory for ACME challenge files
  become: true
  file:
    path: "{{ ACME_CHALLENGE_DIR }}"
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Example ACME challenge index.html
  become: true
  copy:
    content: "<html><body><h1>Hello from WOZiTech Local ACME challenge</h1></body></html>"
    dest: "{{ ACME_CHALLENGE_DIR }}/.well-known/acme-challenge/index.html"
    owner: root
    group: root
    mode: 0644

- name: create the LetsEncrypt container
  become: true
  docker_container:
    name: "{{ LETSENCRYPT_CONTAINER_NAME }}"
    image: gordonchan/auto-letsencrypt
    state: started
    detach: yes
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "{{ SSL_CERTS_DIR }}/{{ wiki_external_domain }}:/etc/nginx/certs"
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - "{{ ACME_CHALLENGE_DIR }}:/var/www"
    env:
      EMAIL: "{{ LETENCYRPT_ADMIN_EMAIL }}"
      DOMAINS: "{{ wiki_external_domain }}"
      CERTS_PATH: /etc/nginx/certs
      SERVER_CONTAINER: "{{ NGINX_CONTAINER_NAME }}"

