# achetemoi web app
---
- name: Install host packages
  become: true
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - "{{ host_os_packages }}"
  when:
    - ansible_pkg_mgr == "yum"

- name: Enable web inbound on public zone
  become: true
  firewalld:
    state: enabled
    zone: public
    port: "{{ achete_proxy_target_port }}/tcp"
    permanent: yes
  register: achete_port_firewalld

- name: Restart firewall for changes to take effect
  become: true
  systemd:
    name: firewalld
    state: restarted
  when: achete_port_firewalld.changed

- name: Ensure directory for web app data
  become: true
  file:
    path: "{{ ACHETE_LOCAL_DATA }}"
    state: directory
    mode: 0777
    owner: vagrant
    group: vagrant
