---
- hosts: all
  vars_files:
    - ../../common/ansible/vars/centosVars.yml
    - vars.yml

  vars:
    nodejs_version: "v8.11.4"
    #nodejs_version: "v10.13.0"
    nvm_parent_path: /opt
    nvm_install_path: "{{ nvm_parent_path }}/nvm"
    nvm_exe_path: "{{ nvm_install_path }}/nvm.sh"

  tasks:
    # - import_tasks: ../../common/ansible/tasks/centosTasks.yml
    # - import_tasks: tasks/extranet-network.yml
    # - import_tasks: tasks/node-native.yml
    - import_tasks: tasks/mongodb-simple-local.yml
