---
- hosts: all
  vars_files:
    - vars.yml
  tasks:
    - import_tasks: commonTasks.yml

    - name: Install nginx (reverse)
      become: true
      yum:
        name: nginx
        state: latest
      when: ansible_pkg_mgr == "yum"

    - name: Install squid (forward)
      become: true
      yum:
        name: squid
        state: latest
      when: ansible_pkg_mgr == "yum"
