---
- hosts: all
  vars_files:
    - vars.yml
  tasks:
    - name: update the local repo
      become: true
      yum:
        name: "*"
        state: latest
        #exclude: git*
      when:
        - ansible_pkg_mgr == "yum"
        - os_update is defined
        - os_update == 1
        
    - name: Install default packages
      become: true
      yum:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      with_items:
        - "{{ default_packages }}"
      when: ansible_pkg_mgr == "yum"

    - name: Install nginx (reverse)
      become: true
      yum:
        name: nginx
        state: latest
      when: ansible_pkg_mgr == "yum"

    - name: Install squid (forward)
      become: true
      yum:
        name: squid
        state: latest
      when: ansible_pkg_mgr == "yum"
