network_gw: "10.0.0.2"      # gateway firewall
netmask: "255.255.255.0"
webserver_ip: "10.0.0.21"
webserver2_ip: "10.0.0.22"
forward_proxy_ip: "10.0.0.10"
reverse_proxy_ip: "10.0.0.12"
vault_ip: "10.0.0.31"
nexus_ip: "10.0.0.32"
root_domain: "wozitech-ltd.local"
proxy_hostname: "proxy"
webserver_hostname: "web1"
webserver2_hostname: "web2"
vault_hostname: "vault"
nexus_hostname: "nexus"
proxy_fqdn: "{{ proxy_hostname }}.{{ root_domain}}"
webserver_fqdn: "{{ webserver_hostname }}.{{ root_domain}}"
webserver2_fqdn: "{{ webserver2_hostname }}.{{ root_domain}}"
vault_fqdn: "{{ vault_hostname }}.{{ root_domain}}"
nexus_fqdn: "{{ nexus_hostname }}.{{ root_domain}}"

root_dns: "192.168.1.1"
local_dns: "{{ forward_proxy_ip }}"

wiki_external_domain: wozitech.asuscomm.com
wikitwo_external_domain: wiki.wozitech.myddns.rocks
nexus_external_domain: nexus.wozitech.myddns.rocks
cms_external_domain: cms.wozitech.myddns.rocks
default_external_domain: wozitech.myddns.rocks

wozitech_nexus_proxy: 10.0.0.32:9081
wozitech_nexus_hosted: 10.0.0.32:9080
wiki_proxy_target_port: 8081
cms_proxy_target_port: 8080