network_gw: "10.0.0.2"      # gateway firewall
netmask: "255.255.255.0"
webserver_ip: "10.0.0.20"
proxy_ip: "10.0.0.10"
root_domain: "wozitech-ltd.local"

dns: "192.168.1.1"          # subject to change

default_packages:
  - { name: epel-release, state: latest }
  - { name: net-tools, state: latest }
  - { name: dos2unix, state: latest }
